"""
Automated Google Doc creation test - no manual input required
"""

import os
import sys
from datetime import datetime

# Add robodogcli to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'robodogcli'))

from google_service import GoogleService


def main():
    print("=" * 70)
    print("Automated Google Doc Creation Test")
    print("=" * 70)
    
    # Check for client secret
    client_secret = os.getenv('GOOGLE_CLIENT_SECRET')
    if not client_secret:
        print("\n❌ GOOGLE_CLIENT_SECRET not set!")
        print("\nRun: $env:GOOGLE_CLIENT_SECRET='YOUR_CLIENT_SECRET_HERE'")
        return
    
    print(f"\n✅ Client secret: {client_secret[:15]}...")
    
    # Initialize service
    print("\n📝 Initializing Google service...")
    service = GoogleService()
    service.client_secret = client_secret
    
    # Authenticate
    print("\n🔐 Authenticating...")
    print("Opening browser for authentication...")
    print("Please sign in and grant permissions.")
    print("The browser will redirect to localhost:8080/callback")
    
    try:
        service.authenticate()
        print("\n✅ Authentication successful!")
    except Exception as e:
        print(f"\n❌ Authentication failed: {e}")
        print("\nTroubleshooting:")
        print("1. Make sure you completed the browser sign-in")
        print("2. Check that you clicked 'Allow' for all permissions")
        print("3. Verify the redirect to localhost:8080/callback worked")
        return
    
    # Create document
    print("\n📄 Creating test document...")
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    title = f"Robodog MCP Test - {timestamp}"
    
    content = f"""# Robodog MCP Test Document

**Created:** {timestamp}
**Status:** ✅ Success!

## Test Results

This document was successfully created by the Robodog MCP integration!

### What This Proves:
- ✅ Google OAuth2 authentication works
- ✅ Google Docs API is accessible
- ✅ Document creation is functional
- ✅ MCP integration is ready

### Your Configuration:
- Client ID: [Your Google OAuth Client ID]
- Redirect URI: http://localhost:8080/callback
- Scopes: Docs, Drive, Gmail

## Next Steps

1. ✅ Verify this document in Google Drive
2. Test MCP operations via the MCP handler
3. Integrate with web UI
4. Create automation workflows

---

*Generated by Robodog - AI-powered development assistant*
*Test completed at {timestamp}*
"""
    
    try:
        doc = service.create_document(title, content)
        doc_id = doc.get('documentId')
        doc_title = doc.get('title')
        
        print(f"\n" + "=" * 70)
        print("🎉 SUCCESS! Document Created!")
        print("=" * 70)
        
        print(f"\n📋 Document Details:")
        print(f"   Title: {doc_title}")
        print(f"   ID: {doc_id}")
        
        print(f"\n🔗 Direct Link:")
        print(f"   https://docs.google.com/document/d/{doc_id}/edit")
        
        print(f"\n📁 Find it in:")
        print(f"   1. Google Drive: https://drive.google.com/")
        print(f"      Search: 'Robodog MCP Test'")
        
        if os.path.exists('G:\\My Drive'):
            print(f"\n   2. G: Drive: G:\\My Drive\\")
            print(f"      File: {doc_title}")
            print(f"      (May take a few seconds to sync)")
        
        print(f"\n" + "=" * 70)
        
        # Save document info to file
        info_file = "last_created_doc.txt"
        with open(info_file, 'w') as f:
            f.write(f"Title: {doc_title}\n")
            f.write(f"ID: {doc_id}\n")
            f.write(f"URL: https://docs.google.com/document/d/{doc_id}/edit\n")
            f.write(f"Created: {timestamp}\n")
        
        print(f"\n💾 Document info saved to: {info_file}")
        
        return doc_id
        
    except Exception as e:
        print(f"\n❌ Failed to create document: {e}")
        print(f"\nError details: {type(e).__name__}")
        import traceback
        traceback.print_exc()
        return None


if __name__ == '__main__':
    doc_id = main()
    if doc_id:
        print("\n✅ Test completed successfully!")
        print(f"\nOpen your document:")
        print(f"https://docs.google.com/document/d/{doc_id}/edit")
    else:
        print("\n❌ Test failed. See errors above.")
