"""
Test creating a Google Doc via MCP and verify it in Google Drive
"""

import requests
import json
import os
import sys
from datetime import datetime

# Add robodogcli to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'robodogcli'))

from google_service import GoogleService


MCP_URL = "http://localhost:2500"
TOKEN = "testtoken"


def call_mcp(operation, payload):
    """Call MCP operation"""
    try:
        body = f"{operation} {json.dumps(payload)}"
        response = requests.post(
            MCP_URL,
            headers={
                "Authorization": f"Bearer {TOKEN}",
                "Content-Type": "text/plain"
            },
            data=body,
            timeout=30
        )
        return response.json()
    except Exception as e:
        return {"status": "error", "error": str(e)}


def test_direct_google_service():
    """Test creating a document directly with GoogleService"""
    print("\n" + "=" * 70)
    print("Testing Google Docs Creation - Direct Method")
    print("=" * 70)
    
    # Check for client secret
    client_secret = os.getenv('GOOGLE_CLIENT_SECRET')
    if not client_secret:
        print("\n❌ GOOGLE_CLIENT_SECRET not set!")
        print("\nTo get your client secret:")
        print("1. Go to: https://console.cloud.google.com/apis/credentials")
        print("2. Find your OAuth 2.0 Client ID")
        print("3. Click 'Download JSON' or view the secret")
        print("4. Set it: $env:GOOGLE_CLIENT_SECRET='your_secret_here'")
        print("\nYour Client ID: 837032747486-0dttoe0dfkfrn9m3obimrgboj8i64leu.apps.googleusercontent.com")
        return False
    
    print(f"\n✅ Client secret found: {client_secret[:10]}...")
    
    # Initialize Google service
    print("\n📝 Initializing Google service...")
    service = GoogleService()
    service.client_secret = client_secret
    
    # Authenticate
    print("\n🔐 Starting authentication...")
    print("A browser window will open. Please:")
    print("1. Sign in to your Google account")
    print("2. Grant permissions to the app")
    print("3. You'll be redirected to localhost:8080/callback")
    print("\nPress Enter to start authentication...")
    input()
    
    try:
        service.authenticate()
        print("✅ Authentication successful!")
    except Exception as e:
        print(f"❌ Authentication failed: {e}")
        return False
    
    # Create a test document
    print("\n📄 Creating test document...")
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    title = f"Robodog MCP Test - {timestamp}"
    content = f"""# Robodog MCP Test Document

**Created:** {timestamp}
**Method:** Direct GoogleService API
**Status:** ✅ Success!

## Test Details

This document was created by the Robodog MCP integration test to verify that:
- Google OAuth2 authentication works
- Google Docs API is accessible
- Document creation is successful
- MCP integration is functional

## Next Steps

1. Verify this document appears in your Google Drive
2. Test MCP operations via the MCP handler
3. Integrate with web UI and CLI

---

*Generated by Robodog - AI-powered development assistant*
"""
    
    try:
        doc = service.create_document(title, content)
        doc_id = doc.get('documentId')
        doc_title = doc.get('title')
        
        print(f"\n🎉 SUCCESS! Document created!")
        print(f"\n📋 Document Details:")
        print(f"   Title: {doc_title}")
        print(f"   ID: {doc_id}")
        print(f"\n🔗 View your document:")
        print(f"   https://docs.google.com/document/d/{doc_id}/edit")
        print(f"\n📁 Find it in Google Drive:")
        print(f"   - Go to: https://drive.google.com/")
        print(f"   - Look for: '{doc_title}'")
        print(f"   - Or search: 'Robodog MCP Test'")
        
        # Check if G: drive exists
        if os.path.exists('G:\\'):
            print(f"\n💾 G: Drive detected!")
            print(f"   If Google Drive is synced to G:, look in:")
            print(f"   G:\\My Drive\\")
            print(f"   Search for: {doc_title}")
        
        return True
        
    except Exception as e:
        print(f"\n❌ Failed to create document: {e}")
        return False


def test_mcp_google_doc():
    """Test creating a document via MCP"""
    print("\n" + "=" * 70)
    print("Testing Google Docs Creation - MCP Method")
    print("=" * 70)
    
    # Check MCP server
    print("\n🔍 Checking MCP server...")
    status = call_mcp("GOOGLE_STATUS", {})
    
    if status.get("status") != "ok":
        print(f"❌ MCP server error: {status.get('error')}")
        return False
    
    print(f"✅ MCP server running")
    print(f"   Authenticated: {status.get('authenticated')}")
    print(f"   Has token: {status.get('has_token')}")
    print(f"   Available: {status.get('available')}")
    
    if not status.get('authenticated'):
        print("\n⚠️  Not authenticated with Google via MCP")
        print("   You need to authenticate first using the direct method above")
        return False
    
    # Create document via MCP
    print("\n📄 Creating document via MCP...")
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    title = f"Robodog MCP Test (via MCP) - {timestamp}"
    content = f"# MCP Test\n\nCreated via MCP at {timestamp}"
    
    result = call_mcp("GDOC_CREATE", {
        "title": title,
        "content": content
    })
    
    if result.get("status") == "ok":
        doc = result.get("document", {})
        doc_id = doc.get('documentId')
        print(f"\n🎉 SUCCESS via MCP!")
        print(f"   Document ID: {doc_id}")
        print(f"   URL: https://docs.google.com/document/d/{doc_id}/edit")
        return True
    else:
        print(f"\n❌ MCP creation failed: {result.get('error')}")
        return False


def main():
    """Run tests"""
    print("=" * 70)
    print("Google Docs Creation Test")
    print("=" * 70)
    print("\nThis script will:")
    print("1. Authenticate with Google (if needed)")
    print("2. Create a test document in Google Docs")
    print("3. Show you where to find it")
    
    # Test direct method
    success = test_direct_google_service()
    
    if success:
        print("\n" + "=" * 70)
        print("✅ Direct method successful!")
        print("=" * 70)
        
        # Optionally test MCP method
        print("\n\nWould you like to test the MCP method too? (y/n): ", end="")
        response = input().strip().lower()
        if response == 'y':
            test_mcp_google_doc()
    
    print("\n" + "=" * 70)
    print("Test Complete!")
    print("=" * 70)
    print("\n📁 To find your document:")
    print("   1. Go to https://drive.google.com/")
    print("   2. Search for 'Robodog MCP Test'")
    print("   3. Or check 'My Drive' for recent documents")
    
    if os.path.exists('G:\\'):
        print("\n💾 G: Drive found!")
        print("   If Google Drive Desktop is syncing:")
        print("   - Open: G:\\My Drive\\")
        print("   - Look for: Robodog MCP Test")
        print("   - Sort by: Date modified (newest first)")


if __name__ == '__main__':
    main()
