"""
Test Gmail API - Send and Read Email
"""

import os
import sys
from datetime import datetime
import time

# Add robodogcli to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'robodogcli'))

from google_service import GoogleService


def main():
    print("=" * 70)
    print("Gmail API Test - Send and Read Email")
    print("=" * 70)
    
    # Check for client secret
    client_secret = os.getenv('GOOGLE_CLIENT_SECRET')
    if not client_secret:
        print("\n❌ GOOGLE_CLIENT_SECRET not set!")
        print("\nRun: $env:GOOGLE_CLIENT_SECRET='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'")
        return
    
    print(f"\n✅ Client secret: {client_secret[:15]}...")
    
    # Initialize service
    print("\n📝 Initializing Google service...")
    service = GoogleService()
    service.client_secret = client_secret
    
    # Authenticate (should use existing token from previous test)
    print("\n🔐 Authenticating...")
    try:
        service.authenticate()
        print("✅ Authentication successful!")
    except Exception as e:
        print(f"❌ Authentication failed: {e}")
        return
    
    # Get user's email address for testing
    print("\n📧 What email address should I send the test to?")
    print("   (This will be a test email to yourself)")
    print("   Enter email address: ", end="")
    to_email = input().strip()
    
    if not to_email or '@' not in to_email:
        print("❌ Invalid email address")
        return
    
    # Send test email
    print(f"\n📤 Sending test email to {to_email}...")
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    subject = f"Robodog Gmail Test - {timestamp}"
    body = f"""Hello!

This is a test email from the Robodog MCP Gmail integration.

Test Details:
- Sent: {timestamp}
- Method: Google Gmail API
- Status: ✅ Success!

What This Proves:
✅ Gmail API is enabled and accessible
✅ Email sending works via MCP integration
✅ Authentication is functional
✅ Ready for email automation

Next Steps:
1. Read and organize emails
2. Create automation workflows
3. Integrate with MCP handler
4. Build email management features

---
Generated by Robodog - AI-powered development assistant
Test completed at {timestamp}
"""
    
    try:
        result = service.send_email(to_email, subject, body)
        email_id = result.get('id')
        thread_id = result.get('threadId')
        
        print(f"\n" + "=" * 70)
        print("🎉 SUCCESS! Email Sent!")
        print("=" * 70)
        
        print(f"\n📧 Email Details:")
        print(f"   To: {to_email}")
        print(f"   Subject: {subject}")
        print(f"   Message ID: {email_id}")
        print(f"   Thread ID: {thread_id}")
        
        print(f"\n✅ Check your inbox at: {to_email}")
        print(f"   Subject line: {subject}")
        
        # Wait a moment for email to be processed
        print(f"\n⏳ Waiting 3 seconds for email to be processed...")
        time.sleep(3)
        
        # List recent emails
        print(f"\n📬 Listing your recent emails...")
        emails = service.list_emails(max_results=5)
        
        messages = emails.get('messages', [])
        print(f"\n📊 Found {len(messages)} recent emails:")
        
        for i, msg in enumerate(messages, 1):
            msg_id = msg.get('id')
            print(f"\n   {i}. Message ID: {msg_id}")
            
            # Get full email details
            try:
                email_data = service.get_email(msg_id)
                
                # Extract headers
                payload = email_data.get('payload', {})
                headers = payload.get('headers', [])
                
                subject_header = next((h['value'] for h in headers if h['name'].lower() == 'subject'), 'No Subject')
                from_header = next((h['value'] for h in headers if h['name'].lower() == 'from'), 'Unknown')
                date_header = next((h['value'] for h in headers if h['name'].lower() == 'date'), 'Unknown')
                
                print(f"      From: {from_header}")
                print(f"      Subject: {subject_header}")
                print(f"      Date: {date_header}")
                
                # Check if this is our test email
                if msg_id == email_id:
                    print(f"      ⭐ THIS IS THE TEST EMAIL WE JUST SENT!")
                
            except Exception as e:
                print(f"      (Could not fetch details: {e})")
        
        # Save email info
        info_file = "last_sent_email.txt"
        with open(info_file, 'w') as f:
            f.write(f"To: {to_email}\n")
            f.write(f"Subject: {subject}\n")
            f.write(f"Message ID: {email_id}\n")
            f.write(f"Thread ID: {thread_id}\n")
            f.write(f"Sent: {timestamp}\n")
        
        print(f"\n💾 Email info saved to: {info_file}")
        
        print(f"\n" + "=" * 70)
        print("✅ Gmail Test Complete!")
        print("=" * 70)
        
        print(f"\n📧 Test Results:")
        print(f"   ✅ Email sent successfully")
        print(f"   ✅ Email listing works")
        print(f"   ✅ Email reading works")
        print(f"   ✅ Gmail API fully functional")
        
        print(f"\n📬 Next Steps:")
        print(f"   1. Check your inbox: {to_email}")
        print(f"   2. Verify the test email arrived")
        print(f"   3. Ready to organize emails via MCP!")
        
        return True
        
    except Exception as e:
        print(f"\n❌ Failed to send email: {e}")
        print(f"\nError details: {type(e).__name__}")
        import traceback
        traceback.print_exc()
        
        # Check if Gmail API is enabled
        if "SERVICE_DISABLED" in str(e) or "has not been used" in str(e):
            print(f"\n⚠️  Gmail API is not enabled!")
            print(f"\nEnable it here:")
            print(f"https://console.developers.google.com/apis/api/gmail.googleapis.com/overview?project=837032747486")
        
        return False


if __name__ == '__main__':
    success = main()
    if success:
        print("\n🎉 All Gmail tests passed!")
    else:
        print("\n❌ Gmail test failed. See errors above.")
